#!/usr/bin/env python3
"""
Generate memory layout verification tests for Rust structs.

Parses Rust source files for structs annotated with layout comments and
generates #[cfg(test)] assertion code verifying size, alignment, and
cache-line fit.

Usage:
    python generate_layout_tests.py src/types.rs > src/types_layout_tests.rs
    python generate_layout_tests.py src/ --recursive > tests/layout_tests.rs

Annotation format — add comments above structs:

    /// @layout size=32 align=4
    /// @layout cache_line_fit
    /// @layout gpu_aligned
    #[repr(C)]
    struct Vertex {
        position: [f32; 3],
        normal: [f32; 3],
        uv: [f32; 2],
    }

Supported annotations:
    size=N       — assert size_of::<T>() == N
    align=N      — assert align_of::<T>() == N
    max_size=N   — assert size_of::<T>() <= N
    cache_line_fit — assert size_of::<T>() <= 64
    gpu_aligned  — assert size_of::<T>() % 16 == 0 (WebGPU uniform alignment)
    field_offset=name:N — assert offset_of!(T, name) == N
"""

import re
import sys
import os
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class LayoutAnnotation:
    size: int | None = None
    align: int | None = None
    max_size: int | None = None
    cache_line_fit: bool = False
    gpu_aligned: bool = False
    field_offsets: dict = field(default_factory=dict)


@dataclass
class AnnotatedStruct:
    name: str
    annotation: LayoutAnnotation
    source_file: str
    line_number: int


def parse_annotation(comment_lines: list[str]) -> LayoutAnnotation | None:
    """Parse @layout annotations from doc comments."""
    ann = LayoutAnnotation()
    found = False

    for line in comment_lines:
        match = re.search(r'@layout\s+(.*)', line)
        if not match:
            continue
        found = True
        directives = match.group(1).strip()

        for directive in directives.split():
            if '=' in directive:
                key, value = directive.split('=', 1)
                if key == 'size':
                    ann.size = int(value)
                elif key == 'align':
                    ann.align = int(value)
                elif key == 'max_size':
                    ann.max_size = int(value)
                elif key == 'field_offset':
                    field_name, offset = value.split(':')
                    ann.field_offsets[field_name] = int(offset)
            elif directive == 'cache_line_fit':
                ann.cache_line_fit = True
            elif directive == 'gpu_aligned':
                ann.gpu_aligned = True

    return ann if found else None


def parse_rust_file(filepath: str) -> list[AnnotatedStruct]:
    """Find structs with @layout annotations in a Rust source file."""
    structs = []

    with open(filepath, 'r') as f:
        lines = f.readlines()

    comment_buffer = []
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # Collect doc comments and regular comments
        if line.startswith('///') or line.startswith('//'):
            comment_buffer.append(line)
            i += 1
            continue

        # Skip attributes (like #[repr(C)]) — they sit between comments and struct
        if line.startswith('#['):
            i += 1
            continue

        # Check for struct definition
        struct_match = re.match(r'^pub\s+struct\s+(\w+)', line) or \
                       re.match(r'^struct\s+(\w+)', line)

        if struct_match and comment_buffer:
            annotation = parse_annotation(comment_buffer)
            if annotation:
                structs.append(AnnotatedStruct(
                    name=struct_match.group(1),
                    annotation=annotation,
                    source_file=filepath,
                    line_number=i + 1,
                ))

        # Reset comment buffer when we hit a non-comment, non-attribute line
        if not line.startswith('///') and not line.startswith('//') and not line.startswith('#['):
            comment_buffer = []

        i += 1

    return structs


def generate_tests(structs: list[AnnotatedStruct]) -> str:
    """Generate Rust test code for layout assertions."""
    if not structs:
        return "// No @layout annotations found.\n"

    lines = [
        "// Auto-generated by generate_layout_tests.py",
        "// Re-run after changing struct layouts.",
        "//",
        "// Annotation reference:",
        "//   /// @layout size=32 align=4",
        "//   /// @layout cache_line_fit",
        "//   /// @layout gpu_aligned",
        "",
        "#[cfg(test)]",
        "mod layout_tests {",
        "    use super::*;",
        "    use std::mem::{size_of, align_of};",
        "",
    ]

    for s in structs:
        ann = s.annotation
        test_name = f"verify_{camel_to_snake(s.name)}_layout"

        lines.append(f"    /// Layout test for {s.name} ({s.source_file}:{s.line_number})")
        lines.append(f"    #[test]")
        lines.append(f"    fn {test_name}() {{")

        if ann.size is not None:
            lines.append(
                f'        assert_eq!(size_of::<{s.name}>(), {ann.size}, '
                f'"{s.name} must be exactly {ann.size} bytes");'
            )

        if ann.align is not None:
            lines.append(
                f'        assert_eq!(align_of::<{s.name}>(), {ann.align}, '
                f'"{s.name} must be {ann.align}-byte aligned");'
            )

        if ann.max_size is not None:
            lines.append(
                f'        assert!(size_of::<{s.name}>() <= {ann.max_size}, '
                f'"{s.name} must be at most {ann.max_size} bytes, got {{}}",  size_of::<{s.name}>());'
            )

        if ann.cache_line_fit:
            lines.append(
                f'        assert!(size_of::<{s.name}>() <= 64, '
                f'"{s.name} should fit in a single cache line (64 bytes), got {{}}",  size_of::<{s.name}>());'
            )

        if ann.gpu_aligned:
            lines.append(
                f'        assert_eq!(size_of::<{s.name}>() % 16, 0, '
                f'"{s.name} must be 16-byte aligned for WebGPU uniforms, got size {{}}",  size_of::<{s.name}>());'
            )

        for field_name, offset in ann.field_offsets.items():
            lines.append(
                f'        assert_eq!(std::mem::offset_of!({s.name}, {field_name}), {offset}, '
                f'"{s.name}::{field_name} must be at offset {offset}");'
            )

        lines.append("    }")
        lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def camel_to_snake(name: str) -> str:
    """Convert CamelCase to snake_case."""
    result = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    result = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', result)
    return result.lower()


def find_rust_files(path: str, recursive: bool = False) -> list[str]:
    """Find .rs files at the given path."""
    p = Path(path)
    if p.is_file():
        return [str(p)]
    if recursive:
        return [str(f) for f in p.rglob("*.rs")]
    return [str(f) for f in p.glob("*.rs")]


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    path = sys.argv[1]
    recursive = "--recursive" in sys.argv or "-r" in sys.argv

    files = find_rust_files(path, recursive)
    if not files:
        print(f"No .rs files found at {path}", file=sys.stderr)
        sys.exit(1)

    all_structs = []
    for filepath in files:
        all_structs.extend(parse_rust_file(filepath))

    if not all_structs:
        print(f"No @layout annotations found in {len(files)} file(s)", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(all_structs)} annotated struct(s) in {len(files)} file(s)", file=sys.stderr)
    print(generate_tests(all_structs))


if __name__ == "__main__":
    main()
